[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.27"
eframe = "0.27"
instant = "0.1"
stcp = { git = "https://github.com/vivyir/stcp", rev = "b45dc84" }
aes-gcm = "0.10"
rs_sha512 = "0.1.3"
chrono = "0.4.41"
